sudo: false

language: node_js
node_js:
  - 6
  - 7

cache:
  directories:
    - node_modules

before_install:
  - yarn add codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

script:
  - yarn test:coverage

notifications:
  slack: whiplashmerch:FOOw6JgjbfJEYI8DxCzXSfJo
  webhooks: https://coveralls.io/webhook?repo_token=RLeRWOziIq1pxmhc3OSlPlD069LqB9qDN
